width = 1000
height = 400
background = rgba(24, 24, 27, 0.9)
border_radius = 12
input_background = rgba(39, 39, 42, 0.8)
input_text_color = white
list_item_background_hover = rgba(63, 63, 70, 0.9)
list_item_text_color = #d3d3d3
list_item_text_color_hover = white
