# ============================================================
# HYPRLAND CONFIG — zento
# ============================================================

# Environment variables
source = ~/.config/hypr/conf/env.conf

# Startup applications and services
source = ~/.config/hypr/conf/autostart.conf

# Monitor configuration
source = ~/.config/hypr/conf/monitors.conf

# Keybindings
source = ~/.config/hypr/conf/binds.conf

# Window rules
source = ~/.config/hypr/conf/rules.conf

# Keyboard and input settings
source = ~/.config/hypr/conf/input.conf

# Mouse bindings
source = ~/.config/hypr/conf/mouse.conf

# Animations
source = ~/.config/hypr/conf/animations.conf

# Decoration (rounding, blur, shadows)
source = ~/.config/hypr/conf/decoration.conf


