exec-once = hyprlock
exec-once = hyprpaper
exec-once = awww-daemon &
exec-once = sleep 2 && /home/zento/data/dotfiles/scripts/apply_wallpaper.sh
exec-once = [workspace 9 silent] /home/zento/data/programs/v2rayN-linux-64/v2rayN

exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = swaync
exec-once = waybar
exec-once = udiskie

exec-once = [workspace 1 silent] sleep 2 && zen-browser
exec-once = [workspace 2 silent] sh -c "sleep 3 && AyuGram"
