decoration {
    rounding = 10
    blur {
        enabled = 0
    }
}

# Эти параметры должны быть вне секции decoration!
border_size = 15
col.active_border = rgba(180, 180, 185, 0.6)
col.inactive_border = rgba(39, 39, 42, 1)
