hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("awww-daemon &")
    hl.exec_cmd("sleep 2 && /home/zento/data/dotfiles/scripts/apply_wallpaper.sh")
    hl.exec_cmd("[workspace 9 silent] /home/zento/data/tools/v2rayN-linux-64/v2rayN")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("[workspace 1 silent] sleep 2 && zen-browser")
    hl.exec_cmd("[workspace 2 silent] sh -c \"sleep 3 && AyuGram\"")
end)
