#!/bin/bash

sudo pacman -S --needed --noconfirm \
    mpv \
    hyprland \
    hyprlock \
    base-devel \
    python-pip \
    yazi \
    hyprpolkitagent \
    hypridle \
    hyprpaper \
    waybar \
    rofi \
    kitty \
    dunst \
    swaync \
    cava \
    fish \
    micro \
    neovim \
    thunar \
    telegram-desktop \
    playerctl \
    pavucontrol \
    pipewire \
    pipewire-pulse \
    wireplumber \
    networkmanager \
    network-manager-applet \
    nm-connection-editor \
    wlogout \
    hyprshot \
    udiskie \
    polkit-kde-agent \
    btop \
    htop \
    git \
    curl \
    wget \
    unzip \
    zip \
    tar \
    gzip \
    xz \
    jq \
    ripgrep \
    npm \
    ttf-jetbrains-mono-nerd \
    ttf-font-awesome \
    adwaita-icon-theme \
    qt5ct \
    gwenview \
    ark \
    kcalc \
    breeze \
    qt6ct \
    breeze-gtk
